allowBuilds:
    '@parcel/watcher': true
    '@swc/core': true
    esbuild: true
    lmdb: true
    msgpackr-extract: true
    sharp: true
    tesseract.js: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - lmdb
  - msgpackr-extract
  - sharp
  - tesseract.js