// Generated by wxt
// Types for the #import virtual module
declare module "#imports" {
    export {browser, Browser} from "wxt/browser";
    export {
        storage, StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError
    } from "wxt/utils/storage";
    export {getAppConfig, useAppConfig} from "wxt/utils/app-config";
    export {ContentScriptContext, WxtWindowEventMap} from "wxt/utils/content-script-context";
    export {
        createIframeUi, IframeContentScriptUi, IframeContentScriptUiOptions
    } from "wxt/utils/content-script-ui/iframe";
    export {
        createIntegratedUi, IntegratedContentScriptUi, IntegratedContentScriptUiOptions
    } from "wxt/utils/content-script-ui/integrated";
    export {
        createShadowRootUi, ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions
    } from "wxt/utils/content-script-ui/shadow-root";
    export {
        ContentScriptUi,
        ContentScriptUiOptions,
        ContentScriptOverlayAlignment,
        ContentScriptAppendMode,
        ContentScriptInlinePositioningOptions,
        ContentScriptOverlayPositioningOptions,
        ContentScriptModalPositioningOptions,
        ContentScriptPositioningOptions,
        ContentScriptAnchoredOptions,
        AutoMountOptions,
        StopAutoMount,
        AutoMount
    } from "wxt/utils/content-script-ui/types";
    export {defineAppConfig, WxtAppConfig} from "wxt/utils/define-app-config";
    export {defineBackground} from "wxt/utils/define-background";
    export {defineContentScript} from "wxt/utils/define-content-script";
    export {defineUnlistedScript} from "wxt/utils/define-unlisted-script";
    export {defineWxtPlugin} from "wxt/utils/define-wxt-plugin";
    export {injectScript, ScriptPublicPath, InjectScriptOptions} from "wxt/utils/inject-script";
    export {InvalidMatchPattern, MatchPattern} from "wxt/utils/match-patterns";
    export {
        onActivated,
        onBeforeMount,
        onBeforeUnmount,
        onBeforeUpdate,
        onErrorCaptured,
        onDeactivated,
        onMounted,
        onServerPrefetch,
        onUnmounted,
        onUpdated,
        useAttrs,
        useSlots,
        computed,
        customRef,
        isReadonly,
        isRef,
        isShallow,
        isProxy,
        isReactive,
        markRaw,
        reactive,
        readonly,
        ref,
        shallowReactive,
        shallowReadonly,
        shallowRef,
        triggerRef,
        toRaw,
        toRef,
        toRefs,
        toValue,
        unref,
        watch,
        watchEffect,
        watchPostEffect,
        watchSyncEffect,
        defineComponent,
        defineAsyncComponent,
        getCurrentInstance,
        h,
        inject,
        nextTick,
        provide,
        useCssModule,
        createApp,
        effectScope,
        EffectScope,
        getCurrentScope,
        onScopeDispose,
        Component,
        Slot,
        Slots,
        ComponentPublicInstance,
        ComputedRef,
        DirectiveBinding,
        ExtractDefaultPropTypes,
        ExtractPropTypes,
        ExtractPublicPropTypes,
        InjectionKey,
        PropType,
        Ref,
        ShallowRef,
        MaybeRef,
        MaybeRefOrGetter,
        VNode,
        WritableComputedRef,
        onRenderTracked,
        onRenderTriggered,
        resolveComponent,
        useCssVars,
        useModel,
        getCurrentWatcher,
        onWatcherCleanup,
        useId,
        useTemplateRef
    } from "vue";
    export {fakeBrowser} from "wxt/testing";
    export {default as color, random} from "../src/utils/color";
    export {submitComment} from "../src/utils/comment";
    export {default as getURL} from "../src/utils/getURL";
    export {
        default as http,
        urls,
        types,
        commentGallTypes,
        viewRegex,
        mgall,
        checkMinor,
        checkMini,
        checkPerson,
        galleryType,
        view,
        mergeParamURL,
        galleryTypeName,
        queryString
    } from "../src/utils/http";
    export {default as ip, ISPData, format} from "../src/utils/ip";
    export {sendMessage, onMessage} from "../src/utils/messaging";
    export {default as observe, find, listen} from "../src/utils/observe";
    export {ScrollDetection, ScrollDetection} from "../src/utils/scrollDetection";
    export {
        BLOCK_TYPES,
        MEMO_TYPES,
        blockStorage,
        blockModeStorage,
        memoStorage,
        modulesStorage,
        ModuleState,
        settingsStorage,
        Record,
        RefresherSettings
    } from "../src/utils/storage";
    export {default as toast, show} from "../src/utils/toast";
    export {Nullable, NullableProperties, ObjectEnum} from "../src/utils/types";
    export {default as user, getType, User, User, UserType} from "../src/utils/user";
    export {default as webStorage, get, set, setObject, remove, clear, moduleStorage} from "../src/utils/webStorage";
    export {default as writeClipboard} from "../src/utils/writeClipboard";
}
