// Generated by wxt
export {};
declare global {
    const BLOCK_TYPES: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/storage").BLOCK_TYPES;
    const ContentScriptContext: typeof import("wxt/utils/content-script-context").ContentScriptContext;
    const EffectScope: typeof import("vue").EffectScope;
    const ISPData: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/ip").ISPData;
    const InvalidMatchPattern: typeof import("wxt/utils/match-patterns").InvalidMatchPattern;
    const MEMO_TYPES: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/storage").MEMO_TYPES;
    const MatchPattern: typeof import("wxt/utils/match-patterns").MatchPattern;
    const ModuleState: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/storage").ModuleState;
    const Record: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/storage").Record;
    const RefresherSettings: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/storage").RefresherSettings;
    const ScrollDetection: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/scrollDetection").ScrollDetection;
    const User: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/user").User;
    const blockModeStorage: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/storage").blockModeStorage;
    const blockStorage: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/storage").blockStorage;
    const browser: typeof import("wxt/browser").browser;
    const checkMini: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/http").checkMini;
    const checkMinor: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/http").checkMinor;
    const checkPerson: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/http").checkPerson;
    const clear: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/webStorage").clear;
    const color: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/color").default;
    const commentGallTypes: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/http").commentGallTypes;
    const computed: typeof import("vue").computed;
    const createApp: typeof import("vue").createApp;
    const createIframeUi: typeof import("wxt/utils/content-script-ui/iframe").createIframeUi;
    const createIntegratedUi: typeof import("wxt/utils/content-script-ui/integrated").createIntegratedUi;
    const createShadowRootUi: typeof import("wxt/utils/content-script-ui/shadow-root").createShadowRootUi;
    const customRef: typeof import("vue").customRef;
    const defineAppConfig: typeof import("wxt/utils/define-app-config").defineAppConfig;
    const defineAsyncComponent: typeof import("vue").defineAsyncComponent;
    const defineBackground: typeof import("wxt/utils/define-background").defineBackground;
    const defineComponent: typeof import("vue").defineComponent;
    const defineContentScript: typeof import("wxt/utils/define-content-script").defineContentScript;
    const defineUnlistedScript: typeof import("wxt/utils/define-unlisted-script").defineUnlistedScript;
    const defineWxtPlugin: typeof import("wxt/utils/define-wxt-plugin").defineWxtPlugin;
    const effectScope: typeof import("vue").effectScope;
    const fakeBrowser: typeof import("wxt/testing").fakeBrowser;
    const find: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/observe").find;
    const format: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/ip").format;
    const galleryType: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/http").galleryType;
    const galleryTypeName: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/http").galleryTypeName;
    const get: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/webStorage").get;
    const getAppConfig: typeof import("wxt/utils/app-config").getAppConfig;
    const getCurrentInstance: typeof import("vue").getCurrentInstance;
    const getCurrentScope: typeof import("vue").getCurrentScope;
    const getCurrentWatcher: typeof import("vue").getCurrentWatcher;
    const getType: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/user").getType;
    const getURL: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/getURL").default;
    const h: typeof import("vue").h;
    const http: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/http").default;
    const inject: typeof import("vue").inject;
    const injectScript: typeof import("wxt/utils/inject-script").injectScript;
    const ip: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/ip").default;
    const isProxy: typeof import("vue").isProxy;
    const isReactive: typeof import("vue").isReactive;
    const isReadonly: typeof import("vue").isReadonly;
    const isRef: typeof import("vue").isRef;
    const isShallow: typeof import("vue").isShallow;
    const listen: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/observe").listen;
    const markRaw: typeof import("vue").markRaw;
    const memoStorage: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/storage").memoStorage;
    const mergeParamURL: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/http").mergeParamURL;
    const mgall: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/http").mgall;
    const moduleStorage: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/webStorage").moduleStorage;
    const modulesStorage: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/storage").modulesStorage;
    const nextTick: typeof import("vue").nextTick;
    const observe: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/observe").default;
    const onActivated: typeof import("vue").onActivated;
    const onBeforeMount: typeof import("vue").onBeforeMount;
    const onBeforeUnmount: typeof import("vue").onBeforeUnmount;
    const onBeforeUpdate: typeof import("vue").onBeforeUpdate;
    const onDeactivated: typeof import("vue").onDeactivated;
    const onErrorCaptured: typeof import("vue").onErrorCaptured;
    const onMessage: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/messaging").onMessage;
    const onMounted: typeof import("vue").onMounted;
    const onRenderTracked: typeof import("vue").onRenderTracked;
    const onRenderTriggered: typeof import("vue").onRenderTriggered;
    const onScopeDispose: typeof import("vue").onScopeDispose;
    const onServerPrefetch: typeof import("vue").onServerPrefetch;
    const onUnmounted: typeof import("vue").onUnmounted;
    const onUpdated: typeof import("vue").onUpdated;
    const onWatcherCleanup: typeof import("vue").onWatcherCleanup;
    const provide: typeof import("vue").provide;
    const queryString: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/http").queryString;
    const random: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/color").random;
    const reactive: typeof import("vue").reactive;
    const readonly: typeof import("vue").readonly;
    const ref: typeof import("vue").ref;
    const remove: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/webStorage").remove;
    const resolveComponent: typeof import("vue").resolveComponent;
    const sendMessage: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/messaging").sendMessage;
    const set: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/webStorage").set;
    const setObject: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/webStorage").setObject;
    const settingsStorage: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/storage").settingsStorage;
    const shallowReactive: typeof import("vue").shallowReactive;
    const shallowReadonly: typeof import("vue").shallowReadonly;
    const shallowRef: typeof import("vue").shallowRef;
    const show: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/toast").show;
    const storage: typeof import("wxt/utils/storage").storage;
    const submitComment: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/comment").submitComment;
    const toRaw: typeof import("vue").toRaw;
    const toRef: typeof import("vue").toRef;
    const toRefs: typeof import("vue").toRefs;
    const toValue: typeof import("vue").toValue;
    const toast: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/toast").default;
    const triggerRef: typeof import("vue").triggerRef;
    const types: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/http").types;
    const unref: typeof import("vue").unref;
    const urls: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/http").urls;
    const useAppConfig: typeof import("wxt/utils/app-config").useAppConfig;
    const useAttrs: typeof import("vue").useAttrs;
    const useCssModule: typeof import("vue").useCssModule;
    const useCssVars: typeof import("vue").useCssVars;
    const useId: typeof import("vue").useId;
    const useModel: typeof import("vue").useModel;
    const useSlots: typeof import("vue").useSlots;
    const useTemplateRef: typeof import("vue").useTemplateRef;
    const user: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/user").default;
    const view: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/http").view;
    const viewRegex: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/http").viewRegex;
    const watch: typeof import("vue").watch;
    const watchEffect: typeof import("vue").watchEffect;
    const watchPostEffect: typeof import("vue").watchPostEffect;
    const watchSyncEffect: typeof import("vue").watchSyncEffect;
    const webStorage: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/webStorage").default;
    const writeClipboard: typeof import("C:/Dev/DCRefresher-Reborn/src/utils/writeClipboard").default;
}
// for type re-export
declare global {
    // @ts-ignore
    export type {Browser} from "wxt/browser";
    import("wxt/browser");
    // @ts-ignore
    export type {
        StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError
    } from "wxt/utils/storage";
    import("wxt/utils/storage");
    // @ts-ignore
    export type {WxtWindowEventMap} from "wxt/utils/content-script-context";
    import("wxt/utils/content-script-context");
    // @ts-ignore
    export type {IframeContentScriptUi, IframeContentScriptUiOptions} from "wxt/utils/content-script-ui/iframe";
    import("wxt/utils/content-script-ui/iframe");
    // @ts-ignore
    export type {
        IntegratedContentScriptUi, IntegratedContentScriptUiOptions
    } from "wxt/utils/content-script-ui/integrated";
    import("wxt/utils/content-script-ui/integrated");
    // @ts-ignore
    export type {
        ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions
    } from "wxt/utils/content-script-ui/shadow-root";
    import("wxt/utils/content-script-ui/shadow-root");
    // @ts-ignore
    export type {
        ContentScriptUi,
        ContentScriptUiOptions,
        ContentScriptOverlayAlignment,
        ContentScriptAppendMode,
        ContentScriptInlinePositioningOptions,
        ContentScriptOverlayPositioningOptions,
        ContentScriptModalPositioningOptions,
        ContentScriptPositioningOptions,
        ContentScriptAnchoredOptions,
        AutoMountOptions,
        StopAutoMount,
        AutoMount
    } from "wxt/utils/content-script-ui/types";
    import("wxt/utils/content-script-ui/types");
    // @ts-ignore
    export type {WxtAppConfig} from "wxt/utils/define-app-config";
    import("wxt/utils/define-app-config");
    // @ts-ignore
    export type {ScriptPublicPath, InjectScriptOptions} from "wxt/utils/inject-script";
    import("wxt/utils/inject-script");
    // @ts-ignore
    export type {
        Component,
        Slot,
        Slots,
        ComponentPublicInstance,
        ComputedRef,
        DirectiveBinding,
        ExtractDefaultPropTypes,
        ExtractPropTypes,
        ExtractPublicPropTypes,
        InjectionKey,
        PropType,
        Ref,
        ShallowRef,
        MaybeRef,
        MaybeRefOrGetter,
        VNode,
        WritableComputedRef
    } from "vue";
    import("vue");
    // @ts-ignore
    export type {ScrollDetection} from "C:/Dev/DCRefresher-Reborn/src/utils/scrollDetection";
    import("C:/Dev/DCRefresher-Reborn/src/utils/scrollDetection");
    // @ts-ignore
    export type {Nullable, NullableProperties, ObjectEnum} from "C:/Dev/DCRefresher-Reborn/src/utils/types";
    import("C:/Dev/DCRefresher-Reborn/src/utils/types");
    // @ts-ignore
    export type {User, UserType} from "C:/Dev/DCRefresher-Reborn/src/utils/user";
    import("C:/Dev/DCRefresher-Reborn/src/utils/user");
}
// for vue template auto import
import {UnwrapRef} from "vue";

declare module "vue" {
    interface ComponentCustomProperties {
        readonly BLOCK_TYPES: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/storage")["BLOCK_TYPES"]>;
        readonly ContentScriptContext: UnwrapRef<typeof import("wxt/utils/content-script-context")["ContentScriptContext"]>;
        readonly EffectScope: UnwrapRef<typeof import("vue")["EffectScope"]>;
        readonly ISPData: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/ip")["ISPData"]>;
        readonly InvalidMatchPattern: UnwrapRef<typeof import("wxt/utils/match-patterns")["InvalidMatchPattern"]>;
        readonly MEMO_TYPES: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/storage")["MEMO_TYPES"]>;
        readonly MatchPattern: UnwrapRef<typeof import("wxt/utils/match-patterns")["MatchPattern"]>;
        readonly ModuleState: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/storage")["ModuleState"]>;
        readonly Record: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/storage")["Record"]>;
        readonly RefresherSettings: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/storage")["RefresherSettings"]>;
        readonly ScrollDetection: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/scrollDetection")["ScrollDetection"]>;
        readonly User: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/user")["User"]>;
        readonly blockModeStorage: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/storage")["blockModeStorage"]>;
        readonly blockStorage: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/storage")["blockStorage"]>;
        readonly browser: UnwrapRef<typeof import("wxt/browser")["browser"]>;
        readonly checkMini: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/http")["checkMini"]>;
        readonly checkMinor: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/http")["checkMinor"]>;
        readonly checkPerson: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/http")["checkPerson"]>;
        readonly clear: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/webStorage")["clear"]>;
        readonly color: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/color")["default"]>;
        readonly commentGallTypes: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/http")["commentGallTypes"]>;
        readonly computed: UnwrapRef<typeof import("vue")["computed"]>;
        readonly createApp: UnwrapRef<typeof import("vue")["createApp"]>;
        readonly createIframeUi: UnwrapRef<typeof import("wxt/utils/content-script-ui/iframe")["createIframeUi"]>;
        readonly createIntegratedUi: UnwrapRef<typeof import("wxt/utils/content-script-ui/integrated")["createIntegratedUi"]>;
        readonly createShadowRootUi: UnwrapRef<typeof import("wxt/utils/content-script-ui/shadow-root")["createShadowRootUi"]>;
        readonly customRef: UnwrapRef<typeof import("vue")["customRef"]>;
        readonly defineAppConfig: UnwrapRef<typeof import("wxt/utils/define-app-config")["defineAppConfig"]>;
        readonly defineAsyncComponent: UnwrapRef<typeof import("vue")["defineAsyncComponent"]>;
        readonly defineBackground: UnwrapRef<typeof import("wxt/utils/define-background")["defineBackground"]>;
        readonly defineComponent: UnwrapRef<typeof import("vue")["defineComponent"]>;
        readonly defineContentScript: UnwrapRef<typeof import("wxt/utils/define-content-script")["defineContentScript"]>;
        readonly defineUnlistedScript: UnwrapRef<typeof import("wxt/utils/define-unlisted-script")["defineUnlistedScript"]>;
        readonly defineWxtPlugin: UnwrapRef<typeof import("wxt/utils/define-wxt-plugin")["defineWxtPlugin"]>;
        readonly effectScope: UnwrapRef<typeof import("vue")["effectScope"]>;
        readonly fakeBrowser: UnwrapRef<typeof import("wxt/testing")["fakeBrowser"]>;
        readonly find: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/observe")["find"]>;
        readonly format: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/ip")["format"]>;
        readonly galleryType: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/http")["galleryType"]>;
        readonly galleryTypeName: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/http")["galleryTypeName"]>;
        readonly get: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/webStorage")["get"]>;
        readonly getAppConfig: UnwrapRef<typeof import("wxt/utils/app-config")["getAppConfig"]>;
        readonly getCurrentInstance: UnwrapRef<typeof import("vue")["getCurrentInstance"]>;
        readonly getCurrentScope: UnwrapRef<typeof import("vue")["getCurrentScope"]>;
        readonly getCurrentWatcher: UnwrapRef<typeof import("vue")["getCurrentWatcher"]>;
        readonly getType: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/user")["getType"]>;
        readonly getURL: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/getURL")["default"]>;
        readonly h: UnwrapRef<typeof import("vue")["h"]>;
        readonly http: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/http")["default"]>;
        readonly inject: UnwrapRef<typeof import("vue")["inject"]>;
        readonly injectScript: UnwrapRef<typeof import("wxt/utils/inject-script")["injectScript"]>;
        readonly ip: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/ip")["default"]>;
        readonly isProxy: UnwrapRef<typeof import("vue")["isProxy"]>;
        readonly isReactive: UnwrapRef<typeof import("vue")["isReactive"]>;
        readonly isReadonly: UnwrapRef<typeof import("vue")["isReadonly"]>;
        readonly isRef: UnwrapRef<typeof import("vue")["isRef"]>;
        readonly isShallow: UnwrapRef<typeof import("vue")["isShallow"]>;
        readonly listen: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/observe")["listen"]>;
        readonly markRaw: UnwrapRef<typeof import("vue")["markRaw"]>;
        readonly memoStorage: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/storage")["memoStorage"]>;
        readonly mergeParamURL: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/http")["mergeParamURL"]>;
        readonly mgall: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/http")["mgall"]>;
        readonly moduleStorage: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/webStorage")["moduleStorage"]>;
        readonly modulesStorage: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/storage")["modulesStorage"]>;
        readonly nextTick: UnwrapRef<typeof import("vue")["nextTick"]>;
        readonly observe: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/observe")["default"]>;
        readonly onActivated: UnwrapRef<typeof import("vue")["onActivated"]>;
        readonly onBeforeMount: UnwrapRef<typeof import("vue")["onBeforeMount"]>;
        readonly onBeforeUnmount: UnwrapRef<typeof import("vue")["onBeforeUnmount"]>;
        readonly onBeforeUpdate: UnwrapRef<typeof import("vue")["onBeforeUpdate"]>;
        readonly onDeactivated: UnwrapRef<typeof import("vue")["onDeactivated"]>;
        readonly onErrorCaptured: UnwrapRef<typeof import("vue")["onErrorCaptured"]>;
        readonly onMessage: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/messaging")["onMessage"]>;
        readonly onMounted: UnwrapRef<typeof import("vue")["onMounted"]>;
        readonly onRenderTracked: UnwrapRef<typeof import("vue")["onRenderTracked"]>;
        readonly onRenderTriggered: UnwrapRef<typeof import("vue")["onRenderTriggered"]>;
        readonly onScopeDispose: UnwrapRef<typeof import("vue")["onScopeDispose"]>;
        readonly onServerPrefetch: UnwrapRef<typeof import("vue")["onServerPrefetch"]>;
        readonly onUnmounted: UnwrapRef<typeof import("vue")["onUnmounted"]>;
        readonly onUpdated: UnwrapRef<typeof import("vue")["onUpdated"]>;
        readonly onWatcherCleanup: UnwrapRef<typeof import("vue")["onWatcherCleanup"]>;
        readonly provide: UnwrapRef<typeof import("vue")["provide"]>;
        readonly queryString: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/http")["queryString"]>;
        readonly random: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/color")["random"]>;
        readonly reactive: UnwrapRef<typeof import("vue")["reactive"]>;
        readonly readonly: UnwrapRef<typeof import("vue")["readonly"]>;
        readonly ref: UnwrapRef<typeof import("vue")["ref"]>;
        readonly remove: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/webStorage")["remove"]>;
        readonly resolveComponent: UnwrapRef<typeof import("vue")["resolveComponent"]>;
        readonly sendMessage: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/messaging")["sendMessage"]>;
        readonly set: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/webStorage")["set"]>;
        readonly setObject: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/webStorage")["setObject"]>;
        readonly settingsStorage: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/storage")["settingsStorage"]>;
        readonly shallowReactive: UnwrapRef<typeof import("vue")["shallowReactive"]>;
        readonly shallowReadonly: UnwrapRef<typeof import("vue")["shallowReadonly"]>;
        readonly shallowRef: UnwrapRef<typeof import("vue")["shallowRef"]>;
        readonly show: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/toast")["show"]>;
        readonly storage: UnwrapRef<typeof import("wxt/utils/storage")["storage"]>;
        readonly submitComment: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/comment")["submitComment"]>;
        readonly toRaw: UnwrapRef<typeof import("vue")["toRaw"]>;
        readonly toRef: UnwrapRef<typeof import("vue")["toRef"]>;
        readonly toRefs: UnwrapRef<typeof import("vue")["toRefs"]>;
        readonly toValue: UnwrapRef<typeof import("vue")["toValue"]>;
        readonly toast: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/toast")["default"]>;
        readonly triggerRef: UnwrapRef<typeof import("vue")["triggerRef"]>;
        readonly types: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/http")["types"]>;
        readonly unref: UnwrapRef<typeof import("vue")["unref"]>;
        readonly urls: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/http")["urls"]>;
        readonly useAppConfig: UnwrapRef<typeof import("wxt/utils/app-config")["useAppConfig"]>;
        readonly useAttrs: UnwrapRef<typeof import("vue")["useAttrs"]>;
        readonly useCssModule: UnwrapRef<typeof import("vue")["useCssModule"]>;
        readonly useCssVars: UnwrapRef<typeof import("vue")["useCssVars"]>;
        readonly useId: UnwrapRef<typeof import("vue")["useId"]>;
        readonly useModel: UnwrapRef<typeof import("vue")["useModel"]>;
        readonly useSlots: UnwrapRef<typeof import("vue")["useSlots"]>;
        readonly useTemplateRef: UnwrapRef<typeof import("vue")["useTemplateRef"]>;
        readonly user: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/user")["default"]>;
        readonly view: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/http")["view"]>;
        readonly viewRegex: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/http")["viewRegex"]>;
        readonly watch: UnwrapRef<typeof import("vue")["watch"]>;
        readonly watchEffect: UnwrapRef<typeof import("vue")["watchEffect"]>;
        readonly watchPostEffect: UnwrapRef<typeof import("vue")["watchPostEffect"]>;
        readonly watchSyncEffect: UnwrapRef<typeof import("vue")["watchSyncEffect"]>;
        readonly webStorage: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/webStorage")["default"]>;
        readonly writeClipboard: UnwrapRef<typeof import("C:/Dev/DCRefresher-Reborn/src/utils/writeClipboard")["default"]>;
    }
}
