// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
    export type PublicPath =
        | ""
        | "/"
        | "/assets/block.webp"
        | "/assets/change.webp"
        | "/assets/close.webp"
        | "/assets/dccon.webp"
        | "/assets/delete.webp"
        | "/assets/downvote.webp"
        | "/assets/newtab.webp"
        | "/assets/pin.webp"
        | "/assets/refresh.webp"
        | "/assets/share.webp"
        | "/assets/upvote.webp"
        | "/assets/write.webp"
        | "/background.js"
        | "/content-scripts/content.js"
        | "/content-scripts/grecaptcha.js"
        | "/icons/128.png"
        | "/icons/16.png"
        | "/icons/32.png"
        | "/icons/48.png"
        | "/popup.html"
    type HtmlPublicPath = Extract<PublicPath, `${string}.html`>

    export interface WxtRuntime {
        getURL(path: PublicPath): string;

        getURL(path: `${HtmlPublicPath}${string}`): string;
    }
}
