name: Release
on:
    push:
        tags:
            - "*.*.*"

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v6

            -   name: Setup pnpm
                uses: pnpm/action-setup@v4

            -   name: Setup Node
                uses: actions/setup-node@v6
                with:
                    node-version: latest
                    cache: pnpm

            -   name: Install Dependencies
                run: pnpm install

            -   name: Zip extensions
                run: |
                    pnpm zip
                    pnpm zip:firefox

            -   name: Release
                uses: softprops/action-gh-release@v2
                with:
                    files: |
                        .output/firefox-mv2.zip
                        .output/chrome-mv3.zip
                    generate_release_notes: true

            -   name: Submit to stores
                run: |
                    pnpm wxt submit \
                      --chrome-zip .output/chrome-mv3.zip \
                      --firefox-zip .output/firefox-mv2.zip --firefox-sources-zip .output/firefox-mv2-src.zip
                env:
                    CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
                    CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
                    CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
                    CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
                    FIREFOX_EXTENSION_ID: ${{ secrets.FIREFOX_EXTENSION_ID }}
                    FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
                    FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}