name: Release
on:
    push:
        tags:
            - "*.*.*"

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v6

            -   name: Setup pnpm
                uses: pnpm/action-setup@v6

            -   name: Setup Node
                uses: actions/setup-node@v6
                with:
                    node-version: latest
                    cache: pnpm

            -   name: Install Dependencies
                run: pnpm install --frozen-lockfile

            -   name: Build
                run: |
                    pnpm build

            -   name: Release
                uses: softprops/action-gh-release@v2
                with:
                    files: |
                        build/firefox-mv2-prod.zip
                        build/chrome-mv3-prod.zip
                    generate_release_notes: true

            -   name: Compress Source Code
                run: |
                    zip -r src.zip src

            -   name: Browser Platform Publish
                uses: PlasmoHQ/bpp@v3
                with:
                    keys: ${{ secrets.BPP_KEYS }}